### PR TITLE
Option to post images directly to Slack

### PR DESCRIPTION
**Pull request by sillyfrog**
Further to my previous PR, this one should hopefully be much lighter in that I'm now using the Slacker module and Slack API token.

This provides image posting directly to Slack, and can optionally replace posted progress messages so there is not a screen full of updates.

It also includes a new `eta` token.

### CODE REVIEW

**Comment by fraschetti** [comment]
Hi @sillyfrog 

Part of the reason it's taken me a while to get to this PR is because you've submitted both the "Black" formatting changes and your actual code changes in the same submission.
I could run the current src through Black and use that to do a proper diff but even then, it's typically frowned upon to have both the formatting + code change blended into one submission.

Time permitting I may find time to resolve this but if not, feel free to take a stab at it yourself.

**Comment by sillyfrog** [comment]
Aggg - I had that in the last one, but forgot to do the extra commit this time (I have it as part of my editors, so forget about it) when I put in the new PR.
When I get a chance I can try again (but I'll probably do it as a new PR with multiple commits if that works for you?)

**Comment by rassie** [comment]
Any news on this one?

**Comment by sillyfrog** [comment]
@fraschetti I have now created a new PR as requested with the PEP8/Black changes in a separate commit to my actual changes in #29. Cheers.

**Pull request closed without merging**
